### ISSUE TITLE
`resolve`, confusing behaviour

### ISSUE THREAD

**Issue by AltGr** [mirage/ocaml-uri#118]
```
# Uri.resolve "http" (Uri.of_string "foo") (Uri.of_string "bar") |> Uri.to_string
- : string = "bar"
# Uri.resolve "http" (Uri.of_string "../foo") (Uri.of_string "bar") |> Uri.to_string
- : string = "../bar"
# Uri.resolve "http" (Uri.of_string "foo/..") (Uri.of_string "bar") |> Uri.to_string
- : string = "foo/bar"
```

Apparently, everything that's not followed by a `/` in the base URI is completely ignored. Is this the expected behaviour ?

**Comment by dsheets** [comment]
Yes, see <https://tools.ietf.org/html/rfc3986#section-5.2.3>. From the path "foo", the reference "bar" means "bar". From the path "../foo", the reference "bar" means "../bar". From the path "foo/..", the reference "bar" means "foo/bar". If you wish to refer to directories, ensure that they end in "/" or 5.2.3 will remove the trailing path segment.
