### ISSUE TITLE
@ not encoded as %40

### ISSUE THREAD

**Issue by sgrove** [mirage/ocaml-uri#145]
I don't seem to be able to construct a uri that has a `%40` in the query, e.g.:

```
Reason # Uri.of_string("https://google.com?test=%40");
- : Uri.t = https://google.com?test=@
```

When talking to some APIs, I need to be able to percent-encode `@` as `%40` - is there a quick way to do so?

**Comment by avsm** [comment]
Did you find a solution for this @sgrove? Is #146 relevant?
