### ISSUE TITLE
Is it possible to split ocaml-uri to avoid the dependency on ocaml-re ? 

### ISSUE THREAD

**Issue by dbuenzli** [mirage/ocaml-uri#21]
Question in the title.

**Comment by rgrinberg** [comment]
@dsheets is this still a useful goal? We've ended up gaining dependencies rather than losing them.

Note that I think it's a bad thing.

**Comment by dsheets** [comment]
Yes, I think it is. Ideally, we would have a bespoke parser for URIs as many of the worst edge cases can't be captured with regexes. There is quite a lot of work to be done looking at the variety of specifications claiming to standardize URL/URI parsing, importing test cases, deciding on appropriate compromises, and implementing the edge cases. Removing the dependency on `ocaml-re` is one component of that work.

**Comment by dbuenzli** [comment]
> Ideally, we would have a bespoke parser for URIs as many of the worst edge cases can't be captured with regexes.

FWIW I always found URI parsing through regexps being a rather dubious approach (well any kind of regexp parsing is in fact, it leads to write-only programs).
