### ISSUE TITLE
Remove hard dependency on camlp4

### ISSUE THREAD

**Issue by whitequark** [mirage/ocaml-uri#56]
The dependency stems from `with sexp`.

**Comment by hcarty** [comment]
The dependency on a pre-processor (currently ppx rather than camlp4) makes cross-compilation of `Uri` with @whitequark's `opam-cross-windows` much more complicated than it would otherwise be due to all the extra dependencies.  How feasible would it be to make the sexp pieces completely optional, now that the move has been made from camlp4 to ppx?

**Comment by hcarty** [comment]
Making the library compile looks relatively straightforward - this seems to a be a minimal diff to "just" remove sexp functions, ignoring tests.

```diff
diff --git a/_oasis b/_oasis
index 9a9d30b..c21278e 100644
--- a/_oasis
+++ b/_oasis
@@ -20,8 +20,8 @@ Flag allservices
 Library uri
   Path:       lib
   Modules:    Uri,Uri_re
-  BuildDepends: re.posix,stringext,sexplib,ppx_sexp_conv
-  XMETARequires: re.posix,stringext,sexplib
+  BuildDepends: re.posix,stringext
+  XMETARequires: re.posix,stringext
 
 Library services
   Path:       lib
@@ -68,7 +68,7 @@ Executable test_runner
   Custom:             true
   CompiledObject:     best
   Install:            false
-  BuildDepends:       uri,oUnit (>= 1.0.2), sexplib
+  BuildDepends:       uri,oUnit (>= 1.0.2)
 
 Test test_runner
   Run$:               flag(tests)
diff --git a/lib/uri.ml b/lib/uri.ml
index 46fbb32..53f4dbf 100644
--- a/lib/uri.ml
+++ b/lib/uri.ml
@@ -16,9 +16,6 @@
  *
  *)
 
-open Sexplib.Std
-open Sexplib.Conv (* Workaround for bug in Sexplib when used without Core *)
-
 type component = [
   | `Scheme
   | `Authority
@@ -429,9 +426,6 @@ module Query = struct
     | KV of kv
     | Raw of string option * kv Lazy.t
 
-  let t_of_sexp sexp = KV (kv_of_sexp sexp)
-  let sexp_of_t = function Raw (_,lazy kv) | KV kv -> sexp_of_kv kv
-
   let compare x y = match x, y with
     | KV kvl, KV kvl'
     | Raw (_, lazy kvl), KV kvl'
@@ -510,13 +504,13 @@ let encoded_of_query ?scheme = Query.encoded_of_query ?scheme
 
 (* Type of the URI, with most bits being optional *)
 type t = {
-  scheme: Pct.decoded sexp_option;
-  userinfo: Userinfo.t sexp_option;
-  host: Pct.decoded sexp_option;
-  port: int sexp_option;
+  scheme: Pct.decoded option;
+  userinfo: Userinfo.t option;
+  host: Pct.decoded option;
+  port: int option;
   path: Path.t;
   query: Query.t;
-  fragment: Pct.decoded sexp_option;
+  fragment: Pct.decoded option;
 } [@@deriving sexp]
 
 let empty = {
```

**Comment by whitequark** [comment]
@hcarty In these cases I prefer the "kill it with fire" approach, i.e. `sed -e s/with sexp// && diff -buRN ... >patches/...`, since anything depending on both uri and sexp won't be usable with such option turned off anyway, and so there's no harm in simply ripping it out instead.

**Comment by hcarty** [comment]
@whitequark Good point.  Once/if I do this for `opam-cross-windows` I'll submit a PR there with the relevant pieces patched out.

**Comment by rgrinberg** [comment]
The patch seems a bit excessive. Isn't it enough to just skip the ppx preprocessing step? I.e. turn off ppx_deriving and ppx_sexp_conv?

**Comment by hcarty** [comment]
@rgrinberg Removing all references to the sexp modules avoids the need to port sexplib and js-build-tools.  Neither should be that difficult but I don't personally have any use for them.

If someone else does the porting work then I'd be happy to simplify the patch accordingly.

**Comment by hannesm** [comment]
closing, uri now uses ppx. if i missed something in the thread which still needs to be done, please reopen or open a new issue.
