### ISSUE TITLE
Functions for extracting non-key-value query string

### ISSUE THREAD

**Issue by whitequark** [mirage/ocaml-uri#57]
I.e. I want to get just the query string. Since the RFC does not even specify the key-value form at all, I'm surprised it is not possible to access it.

**Comment by dsheets** [comment]
This is an oversight and should definitely be included in the next minor rev.

Your immediate options are:

1. let the parse occurs and reconstruct the query string from that (should be faithful)
2. take everything between '?' and '#' or the end-of-string
