### ISSUE TITLE
Uri.encoded_of_query and nulls

### ISSUE THREAD

**Issue by trevorsummerssmith** [mirage/ocaml-uri#66]
I'm not sure if this use case should be supported but I wanted to bring it up. The AWS S3 API requires signing of the request. This signing requires that query parameters that are null are presented with an equal sign.

S3 wants: https://foo.com?a=&b=4&c=
Uri.encoded_of_query would return: "a&b=4&c"

Should there be a configuration parameter in Uri to allow one to deal with null query params differently?

It seems to me (probably correct) that one would save on a few bytes in the general case. I didn't take time yet to look at what the standards say.

Interested to hear your thoughts. Thanks.

Trevor

**Comment by marklrh** [comment]
Is the requirement of adding equal sign specified in this [webpage](http://docs.aws.amazon.com/AmazonS3/latest/dev/RESTAuthentication.html#RESTAuthenticationQueryStringAuth) or somewhere else? 

After some study, I think no standard, neither [RFC 3986](http://tools.ietf.org/html/rfc3986#section-3.4) nor [RFC 2616](http://tools.ietf.org/html/rfc2616), mentions about this "adding an extra equal sign" requirement.

I think we can add an optional argument, when turned on, that can fulfill this requirement

**Comment by dsheets** [comment]
```ocaml
# let uri = Uri.of_string "https://foo.com?a=&b=4&c=";;
val uri : Uri.t = https://foo.com?a=&b=4&c=

# Uri.encoded_of_query (Uri.query uri);;
- : bytes = "a=&b=4&c="
```

What is the issue, exactly?

**Comment by marklrh** [comment]
I guess he means, for the following function call
````OCaml
Uri.encoded_of_query [("a",["a1";"a2"]);("b",["b1"]); ("c", [])];;
````
S3 wants
````OCaml
"a=a1,a2&b=b1&c="
````
but ``encoded_of_query`` gives
````OCaml
"a=a1,a2&b=b1&c"
````

**Comment by trevorsummerssmith** [comment]
@marklrh That is correct. @dsheets Does that clarify the issue?

The docs are confusing! There's no non-aws-standard that I am aware of which specifies this. The required equal sign is shown on this documentation page (sorry for not linking that in the original post):

http://docs.aws.amazon.com/AmazonS3/latest/API/sig-v4-header-based-auth.html

**Comment by dsheets** [comment]
```ocaml
# Uri.encoded_of_query [("a",["a1";"a2"]);("b",["b1"]); ("c", [""])];;
- : bytes = "a=a1,a2&b=b1&c="
```

Is this OK?

**Comment by marklrh** [comment]
@dsheets 

This [hack](https://github.com/mirage/ocaml-cohttp/pull/294/files#diff-5acecd43e2f22342d9eae71daaa77470R112) did use the method you suggested

**Comment by dsheets** [comment]
@marklrh No, I don't believe it does. @trevorsummerssmith needs to use `Uri.with_query`, `List.map`, and `Uri.query` in a composition to transform `[]` into `[""]`.

I'm not sure how you (pl) are suggesting changing this library or what you think is missing. The query API fully supports distinguishing valueless keys from keys with empty values -- at quite a complexity cost, I might add. What (more) should be done?

**Comment by dsheets** [comment]
Maybe `map_query`?

**Comment by marklrh** [comment]
My mistake. My understanding is that we can turn empty value list ``[]`` into ``[""]`` and problem will be solved

**Comment by trevorsummerssmith** [comment]
@dsheets I didn't see that the library distinguished between `[]` and `[""]` originally. I see that there is documentation to this effect on the `get_query_param'` function. I agree that given the library does distinguish between these two nothing more should be done, and that the user can easily map between these values if they need.

I would suggest adding more centralized/global documentation about how these things are treated. I don't think it is good that the only place this is currently documented is on the one function. Thoughts?

**Comment by dsheets** [comment]
Yes, documentation needs work. I hope I can find time in April to push on all of the clean-up for `Uri`. I'll leave this issue open to track the query docs.

**Comment by trevorsummerssmith** [comment]
Just so it is here. If one had a uri and wanted to convert it to use explicit nulls the workaround would be:

`  Uri.query uri
  |> List.map
    ~f:(fun (k,v) -> (k, match v with [] -> [""] | x -> x))
  |> Uri.encoded_of_query
`

So yea I think this is a small enough of a thing, and few enough people would want to do it, that this seems reasonable not to add to the api.

**Comment by Richard-Degenne** [comment]
Sorry to reopen such an old issue, but I ran into this problem today and lost quite a bit of time figuring out what was going on.

IMHO, this behavior breaks the principle of least surprise. Even if standards are a bit loose on this particular situation, all real-world applications expects URL-encoded query strings to be formatted as the original issue suggests.

Still IMHO, waiting for users of the library to run into trouble and then only give a work-around is not a great practice.
