### ISSUE TITLE
Provide convenience functions for URNs

### ISSUE THREAD

**Issue by Chris00** [mirage/ocaml-uri#68]
Some convenience functions for URNs would be nice.  I am especially thinking of [urn:uuid](https://en.wikipedia.org/wiki/Universally_unique_identifier):
```
Uri.uuid : Digest.t -> Uri.t
```

**Comment by dbuenzli** [comment]
`md5` digests are not good uuids.

**Comment by dbuenzli** [comment]
FWIW [RFC4122](https://tools.ietf.org/html/rfc4122#section-4.3) explicitly says that `sha1` UUIDs (version 5) should be preferred.

**Comment by Chris00** [comment]
Thanks, did not check.  Then the request become: provide a good `Uri.uuid` and `Uri.md5 : Digest.t -> Uri.t` (the latter using the URN `urn:md5:...`).

**Comment by dsheets** [comment]
I believe these scheme-specific functions (esp. so many of them for URNs) should live in their own package which depends on `uri`. I've put the beginnings of a module to do this at <https://github.com/dsheets/ocaml-urn>.
