### ISSUE TITLE
Uri.pct_encode: single quotes

### ISSUE THREAD

**Issue by Chris00** [mirage/ocaml-uri#84]
Since the URI can be between single quotes in HTML, wouldn't it be a good idea that `Uri.pct_encode` also percent-encodes single quotes?

**Comment by dsheets** [comment]
I believe an application producing `'` delimited URIs in HTML is in error. From [RFC 3986 Sec 2.2](https://tools.ietf.org/html/rfc3986#section-2.2):

> The purpose of reserved characters is to provide a set of delimiting
   characters that are distinguishable from other data within a URI.
   URIs that differ in the replacement of a reserved character with its
   corresponding percent-encoded octet are not equivalent.  Percent-
   encoding a reserved character, or decoding a percent-encoded octet
   that corresponds to a reserved character, will change how the URI is
   interpreted by most applications.  Thus, characters in the reserved
   set are protected from normalization and are therefore safe to be
   used by scheme-specific and producer-specific algorithms for
   delimiting data subcomponents within a URI.

So a generic `pct_encode` call will not do that escaping. When the interface moves to have programmable character sets, you will be able to perform this yourself (but I don't recommend it). If you need to delimit URIs, I suggest using `"` or `<` and `>`.
