### ISSUE TITLE
Installation fails on most recent opam (2016-02-21)

### ISSUE THREAD

**Issue by c-cube** [mirage/ocaml-uri#88]
I tried `opam install uri. Message is:

> ocamlfind: Package `sexplib.syntax' not found
> W: Field 'pkg_sexplib_syntax' is not set: Command ''/home/simon/.opam/4.02.3/bin/ocamlfind' query -format %d sexplib.syntax > '/tmp/oasis-bd53a8.txt'' terminated with error code 2
> E: Cannot find findlib package sexplib.syntax
> E: Failure("1 configuration error")

I suppose the packaging of sexplib has changed, now that ppx replaces camlp4.

**Comment by dsheets** [comment]
Do you have `uri` pinned? #87 is the update for the repo metadata which will move to ppx. The primary opam-repository already contains the sexplib constraint.

**Comment by c-cube** [comment]
No, I don't have uri pinned, nor (as far as I can tell) any of its dependencies.

**Comment by dsheets** [comment]
Have you run `opam update` recently? If you have a local git opam repository, have you pulled from the primary repo recently?

**Comment by c-cube** [comment]
Yes yes, I have run `opam update` and I have, among others, the default repository.

Here is what `opam info uri` returns:

>              package: uri
             version: 1.9.1
          repository: testing
        upstream-url: https://github.com/mirage/ocaml-uri/archive/v1.9.1.tar.gz
       upstream-kind: http
   upstream-checksum: 44a36ed3da245f1fdd5623d17f3d16c5
            homepage: https://github.com/mirage/ocaml-uri
         bug-reports: https://github.com/mirage/ocaml-uri/issues
            dev-repo: https://github.com/mirage/ocaml-uri.git
              author: Anil Madhavapeddy, David Sheets, Rudi Grinberg
             license: ISC
                tags: url, uri, org:mirage, org:xapi-project
             depends: ocamlfind & re & sexplib >= 109.53.00 & base-bytes & type_conv & stringext >= 1.4.0 & ocamlbuild
   installed-version: 
  available-versions: 1.1, 1.3.0, 1.3.1, 1.3.2, 1.3.3, 1.3.4, 1.3.5, 1.3.6, 1.3.8, 1.3.9, 1.3.10, 1.3.11, 1.3.12, 1.3.13, 1.4.0, 1.5.0, 1.6.0, 1.7.0, 1.7.1, 1.7.2, 1.8.0, 1.9.0, 1.9.1
         description: RFC3986 URI/URL parsing library

**Comment by dsheets** [comment]
What is ` repository: testing`?

**Comment by c-cube** [comment]
It's a local clone of the default repository, but it has lower priority. I've just updated it, and now it seems to work (after upgrading and downgrading tons of things, including `downgrade sexplib       113.24.00 to 113.00.00`. I'm still surprised that updating this repo (which should be superseeded by default) changes anything, but thanks!

**Comment by dsheets** [comment]
@c-cube you may want to file an opam bug for that if you have a good reproduction.
