### ISSUE TITLE
Argument ordering prevents chaining

### ISSUE THREAD

**Issue by mor1** [mirage/ocaml-uri#89]
Current argument ordering for `with_*`, having the `Uri.t` parameter first, prevents chaining of the form:

``` ocaml
Uri.(empty |> with_host (Some "hostname") |> with_port (Some 12345))
```

Suggest perhaps either flipping the ordering for `with_*` which will break things, or perhaps introducing equivalent `set_*` values with the flipped order. Thoughts?

**Comment by dbuenzli** [comment]
Why chain ? Why provide so many `with_*` functions ? Simply provide a single function with an optional label for each component.

**Comment by mor1** [comment]
Because I might not always be starting with `Uri.empty` but still wish to update more than one component?

**Comment by dbuenzli** [comment]
> Because I might not always be starting with Uri.empty but still wish to update more than one component?

Precisely. 

```
Uri.with_uri : ?host:string -> ?port:int -> ... -> t -> t 
```

**Comment by mor1** [comment]
Ah! ISWYM. Sorry, misunderstood -- thought you were proposing a single constructor function, not a single `with_uri` function as you describe. Yes, adding a multi-parameter `with_uri` seems reasonable too.

**Comment by hcarty** [comment]
@mor1 Can this be closed now that #97 has been merged?

**Comment by mor1** [comment]
Yes! Thanks-- closing :)

**Comment by hcarty** [comment]
Thanks!
